namespace CMS.Domain.Modules.DoctorProfiles;

public enum SpecializationType
{
    None = 0,
    GeneralPractitioner = 1,
    Cardiologist = 2,
    Dermatologist = 3,
    Endocrinologist = 4,
    Gastroenterologist = 5,
    Neurologist = 6,
    Oncologist = 7,
    OrthopedicSurgeon = 8,
    Pediatrician = 9,
    Psychiatrist = 10,
    Pulmonologist = 11,
    Radiologist = 12,
    Rheumatologist = 13,
    Urologist = 14,
    Ophthalmologist = 15,
    Otolaryngologist = 16,
    Dentist = 17,
    Anesthesiologist = 18,
    ObstetricianGynecologist = 19,
    PlasticSurgeon = 20,
    EmergencyMedicine = 21,
    Geriatrician = 22,
    Hematologist = 23,
    InfectiousDiseaseSpecialist = 24,
    Nephrologist = 25,
    Pathologist = 26,
    SportsMedicine = 27,
    AllergistImmunologist = 28,
    SleepMedicineSpecialist = 29,
    PainManagementSpecialist = 30,
    ThoracicSurgeon = 31,
    VascularSurgeon = 32,
    Geneticist = 33,
    NuclearMedicineSpecialist = 34,
    CriticalCareMedicine = 35,
    PreventiveMedicine = 36
}